### ISSUE TITLE
Test against 2.5.1

### ISSUE THREAD

**Issue by zerocrates** [omeka/plugin-DublinCoreExtended#18]
Use v2.2 of this plugin, stable-2.5 branch of core.

The feature that's potentially problematic with the upgrade is the "Refines Items Search" option

**Comment by zerocrates** [comment]
The specific problem should arise when having that option enabled and doing a search that uses the boolean (particularly OR) advanced search.

You'll need items that have data in the "refinements" for a basic DC element and then do the search for the basic one (i.e., have items with Alternative Title set and do a search for Title).

**Comment by mebrett** [comment]
When the config button "Refines Item Search" is checked, the "OR" operator in advanced search is treated as an "AND" but only for those properties which can be refined (so, it breaks on Title searchers but not creator)
