### ISSUE TITLE
Causing fields to disappear in API calls

### ISSUE THREAD

**Issue by sashafr** [omeka/plugin-DublinCoreExtended#21]
I had DCE turned on for one of my instances and I am also publishing to that instance through the [JSTOR Forum Omeka API Publishing Target](http://support.forum.jstor.org/article/manage-omeka-targets). I noticed that when I am setting up a publishing target in JSTOR Forum, the API call that gets all the elements wasn't returning Subject and Title. I've attached the results of the API call with DCE turned off and turned on. This is the call I am using:

`http://myomekasite.org/api/elements?element_set=1&key=`

[out-DCE-on.txt](https://github.com/omeka/plugin-DublinCoreExtended/files/1974941/out-DCE-on.txt)

[out-DCE-off.txt](https://github.com/omeka/plugin-DublinCoreExtended/files/1974942/out-DCE-off.txt)

**Comment by zerocrates** [comment]
Obviously this is a very late-coming response but, I think what was happening here was just that you had more than 50 elements once you installed the plugin, and with the API page limit being 50, the remaining 5 elements were just on the next page.
