### ISSUE TITLE
Uninstall broken, sometimes

### ISSUE THREAD

**Issue by zerocrates** [omeka/plugin-DublinCoreExtended#5]
See http://omeka.org/forums/topic/dublin-core-extension-error

I'm not sure what this person's initial problem was/is, but the plugin clearly doesn't account for the possibility that the elements it's trying to delete might not exist for whatever reason.

This error prevents the plugin from being uninstalled through the interface.

**Comment by jimsafley** [comment]
Fixed in 2ce184fd18c245de50041ac14bd6fff599e59924
